### ISSUE TITLE
Syntax: Public preprocessing during the preparation phase

### ISSUE THREAD

**Issue by cjpatton** [cjpatton/vdaf#11]
For both prio3 and hits, each round of the preparation phase consists of a step of "preprocessing" of the previous round's messages. This preprocessing step is identical for all of the aggregators. In hits, for example, each aggregator begins each round by summing up the messages from the previous round. From Figure 15 in https://cjpatton.github.io/vdaf/draft-patton-cfrg-vdaf.html#name-preparation-3:
```
    ...
    elif self.step == "sketch round 1" and len(inbound) == 2:
      verifier_1 = Field[l].deocde_vec(inbound[0]) + \             # ADD UP INPUT MESSAGES
                   Field[l].deocde_vec(inbound[1])

      verifier_share_2 = [
        (verifier_1[0] * verifier_1[0] \
         - verifier_1[1] \
         - verifier_1[2]) * self.party_id \
        + A_share * verifer_1[0] \
        + B_share
      ]

      self.step = "sketch round 2"
      return Field[l].encode_vec(verifier_share_2)

    elif self.step == "sketch round 2" and len(inbound) == 2:
      verifier_2 = Field[l].decode_vec(inbound[0]) + \             # ADD UP INPUT MESSAGES
                   Field[l].decode_vec(inbound[1])

      if verifier_2 != 0: raise ERR_INVALID
      return Field[l].encode_vec(self.output_share)
   ...
```
The essence of what's happening here is that, in each round, the aggregators are exchanging additive shares of a single message. prio3 is similar, although each message consists of an XOR-share of as byte string and an additive share of the FLP verifier. From Figure 10:
```
   ...
   elif self.step == "waiting" and len(inbound) == SHARES:
      k_joint_rand = zeros(KEY_SIZE)
      verifier = vec_zeros(VERIFIER_LEN)
      for r_share in inbound:
        (k_joint_rand_share,
         verifier_share) = decode_verifier_share(r_share)

        k_joint_rand ^= k_joint_rand_share                           # ADD UP xor SHARES
        verifer += verifier_share                                    # ADD UP ADDITIVE SHARES

      if k_joint_rand != self.k_joint_rand: raise ERR_INVALID
      if not flp_decide(verifier): raise ERR_INVALID
      return Field.encode_vec(self.output_share)
   ...
```
What we're likely to do in the PPM protocol is have one aggregator -- the Leader -- collect the verifier messages at each round and relay them to the other aggregators. We could save on communication cost if we have the Leader perform this public preprocessing step itself and disseminate the result.

To make this optimization generic, I'd like to propose that we lift the public processing step to an explicit part of the syntax. In particular, we'd change the preparation phase as follows (from Figure 6):
```
   # Each aggregator initializes its preparation state.
    prep_states = []
    for j in range(SHARES):
      prep_states.append(PrepState(
          verify_params[j], agg_param, nonce, input_shares[j]))

    # Aggregators recover their output shares.
-   inbound = []
+   inbound = ""
    for i in range(ROUNDS+1):
      outbound = []
      for j in range(SHARES):
        outbound.append(prep_states[j].next(inbound))
      # This is where we would send messages over the network
      # in a distributed VDAF computation.
-     inbound = outbound
+     inbound = prep_preprocess(j, outbound)

    # The final outputs of validation are the output shares
    # for this input.
    output_shares.append(outbound)
```

I don't think this syntactic change would decrease generality, but I also don't want it to be a nuisance. Maybe it makes sense to not call this out explicitly?

**Comment by bifurcation** [comment]
I actually think this could *increase* generality, since we're adding a stage that transforms outbound shares to some inbound parameter.  In the current framing, that stage has to be the identity transformation, such that the inbound parameter is the set of outbound shares.

The only real trouble I see here is that we don't currently have a name for the actor who would perform this transformation.  And just to confirm -- is this actor really untrusted in the examples we have today?  Or are they trusted in some limited way?

**Comment by cjpatton** [comment]
Who performs this transform will depend on how the VDAF is mapped to a protocol. It ought to be the case that *anyone* can perform this transform without impacting privacy. (We'll need to make this clear in security considerations.)

**Comment by tgeoghegan** [comment]
>What we're likely to do in the PPM protocol is have one aggregator -- the Leader -- collect the verifier messages at each round and relay them to the other aggregators. We could save on communication cost if we have the Leader perform this public preprocessing step itself and disseminate the result.

I think this is a good optimization but IIUC it requires that the PPM leader be able to see all the verifier messages (i.e., Prio proof shares) in the clear, which isn't currently possible because the helper's proof share is inside the HPKE encrypted envelope. So does this change require corresponding PPM changes to move verifier shares out of the encryption envelope, or am I misunderstanding?

**Comment by cjpatton** [comment]
What is being preprocessed is the set of messages passed between the Aggregators, which is not the proof shares. The proof shares are sent by the Clients to the Aggregators. If the Aggregators were to exchanges the proof shares themselves, this would result in a security violation.

**Comment by tgeoghegan** [comment]
The important thing is that this only reduces the complexity of communication if there are more than two aggregators, which is not currently the case in PPM. It's nevertheless a good change.
